### ISSUE TITLE
Prefer using P384 ECC algorithm 

### ISSUE THREAD

**Issue by aminjam** [cloudfoundry/tlsconfig#10]
We've removed the P384 from tlsconfig [here](https://github.com/cloudfoundry/tlsconfig/commit/07274a700fb4c760fba249bb06f682a8c08ef202) due to seeing a lot of timing related failures in CI when we bumped diego-release. We've decided to use the default GO ECC algorithm for right now and generate a story to figure out the best way forward to preferring the recommended set. 

Things we would like to better understand across the board:
- Performance and timing impact
- Security Risks and Benefits as far as TLS is concerned
- OS level impact (windows/linux)

The failures we've seen has been for the clients talking to the servers configured with P384 on top of the list. Below is a list of CI failures we've captured for visibility.

https://diego.ci.cf-app.com/teams/main/pipelines/main/jobs/units-common/builds/1574
https://diego.ci.cf-app.com/teams/main/pipelines/main/jobs/units-windows/builds/1236
https://diego.ci.cf-app.com/teams/main/pipelines/main/jobs/units-postgres/builds/1305

**Comment by mariash** [comment]
Hi @aminjam, do you still need this feature? The team is going into maintainer mode and moving towards managing issues/stories in github and we are directing people to create all issues in diego-release for better visibility. If you still need this please open an issue in diego-release.
